### ISSUE TITLE
Support monolog 2 and laravel 8

### ISSUE THREAD

**Issue by vladamir** [moeinrahimi/monolog-telegram#16]
Laravel requires monolog v2 - could you increase this ` "monolog/monolog": "~1"` to 2 version

**Comment by moeinrahimi** [comment]
sure, let me do some tests first and I will release a new version adding version 2 of monolog.

**Comment by moeinrahimi** [comment]
@vladamir just released a new version.

**Comment by vladamir** [comment]
thank you!
