### ISSUE TITLE
Respect more monolog standard output

### ISSUE THREAD

**Issue by babbomaria** [moeinrahimi/monolog-telegram#4]
Usually in monolog we can print a line like
`BELogger.INFO: Params {"name":"Jane"} {"dummy":"Hello world!"}`

Where 

- BELogger  is the name of the logger
- .INFO is the level of this log row
- Params is the log message
-  {"name":"Jane"}  is the optional attribute 
- {"dummy":"Hello world!"}` is the extra record usually done by processor

using telegram I think could be useful to see the  entire structure of the message
- I can't see the name of the logger
- I think the level is expressed by Icon
- I can see the message
- I can see the attribute
- I can't see the extra record

**Comment by rvalitov** [comment]
Agree

**Comment by moeinrahimi** [comment]
I will take a look to see what can i do on my free time, until then feel free to open PR

**Comment by rvalitov** [comment]
Thank you! I think the best approach is to use the formatter functionality. In this case you can move your current code for styling to a custom formatter class.

**Comment by moeinrahimi** [comment]
@babbomaria 
can you provide example on how do you print logs ? I can see that we have $record['format'] in monolog
which contains the data you mentioned, so my main question is do you want to have access to $record array after you used the logger like this or am i missing something here ? 
``` php
$data = $log->info('hi');
which data contains
Array
(
    [message] => hello world !
    [context] => Array
        (
        )

    [level] => 200
    [level_name] => INFO
    [channel] => TelegramHandler
    [datetime] => DateTime Object
        (
            [date] => 2018-11-13 08:06:23.712723
            [timezone_type] => 3
            [timezone] => UTC
        )

    [extra] => Array
        (
        )

    [formatted] => [2018-11-13 08:06:23] TelegramHandler.INFO: hello world ! [] []

)
```

**Comment by babbomaria** [comment]
> @babbomaria
> can you provide example on how do you print logs ? I can see that we have $record['format'] in monolog
> which contains the data you mentioned, so my main question is do you want to have access to $record array after you used the logger like this or am i missing something here ?
> 
> ```
> $data = $log->info('hi');
> // $data contains
> Array
> (
>     [message] => hello world !
>     [context] => Array
>         (
>         )
> 
>     [level] => 200
>     [level_name] => INFO
>     [channel] => TelegramHandler
>     [datetime] => DateTime Object
>         (
>             [date] => 2018-11-13 08:06:23.712723
>             [timezone_type] => 3
>             [timezone] => UTC
>         )
> 
>     [extra] => Array
>         (
>         )
> 
>     [formatted] => [2018-11-13 08:06:23] TelegramHandler.INFO: hello world ! [] []
> 
> )
> ```

Hi, sorry for delay
I talk only about the output i can see in Telegram.
When I use  your class on my Telegram I obtain

`July 7,2018,10:53 am <icon(related to info)> Params {"name":"Jane"}`

on my log I have
`BELogger.INFO: Params {"name":"Jane"} {"dummy":"Hello world!"}`

on another telegram plugin 
`[host name] [2018-07-07 10:53:42] BELogger.INFO: Params {"name":"Jane"} {"dummy":"Hello world!"}`

It is funny to see the icon IMO there ar no problem, but I don't know how to sho this important infos 

so it is useful to 
- print the logger name i have a lot of them
- print time with seconds 
- print extra infos 
- show data as numeric

**Comment by moeinrahimi** [comment]
@babbomaria 
based on monolog's default formatting style logs should like this , 
```
2018-11-18 07:18:44 TelegramHandler.NOTICE 
🕵️ hello world ! {"username":"Seldaek"}
```
is this what you are looking into ?

**Comment by babbomaria** [comment]
Yes

If I remember correctly,  if you put extra you obtain also the extra part

**Comment by moeinrahimi** [comment]
I'm closing the issue , feel free to re-open it if anything went wrong with timeout option
