### ISSUE TITLE
Timeout option

### ISSUE THREAD

**Issue by rvalitov** [moeinrahimi/monolog-telegram#6]
Can you please add a timeout option for the Web request?

**Comment by moeinrahimi** [comment]
yes sure I will add Ian option to set timeout, I will mention you when the new feature implemented

**Comment by rvalitov** [comment]
Thank you for a fast feedback! Please keep in mind that if you use curl then it has 2 timeout options.

**Comment by moeinrahimi** [comment]
I found these two options for curl timeout . 
are these two enough for setting timeout ?
``` php
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 0); 
curl_setopt($ch, CURLOPT_TIMEOUT, 400); 
```

**Comment by rvalitov** [comment]
Yes that's enough.

**Comment by moeinrahimi** [comment]
I'm closing the issue , feel free to re-open it if anything went wrong with timeout option

**Comment by rvalitov** [comment]
It's almost OK, I made some PRs related to this issue, please have a look:
- #8
- #10
- #11
